# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('REN', 'Rent'), ('BOR', 'Borrow')], max_length=3)),
                ('deposit', models.IntegerField()),
                ('upfrontcost', models.IntegerField()),
                ('rateinterval', models.IntegerField()),
                ('currentavailable', models.IntegerField()),
                ('maxavailable', models.IntegerField()),
                ('pluscode', models.CharField(max_length=10)),
                ('contactinfo', models.TextField()),
                ('details', models.TextField()),
                ('imagecount', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contactinfo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tool_pool.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tool_pool.User'),
        ),
        migrations.AddField(
            model_name='listing',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_pool.User'),
        ),
    ]
